import { createActor } from "@/backend";
import type {
  Folder,
  Id,
  Note,
  NoteFilter,
  NoteInput,
  NotePatch,
  NotesBackend,
  Settings,
  SortOrder,
  Tag,
} from "@/types/notes";
import { DEFAULT_NOTE_FILTER, DEFAULT_SETTINGS } from "@/types/notes";
import { useActor } from "@caffeineai/core-infrastructure";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { create } from "zustand";
import { persist } from "zustand/middleware";

/* -------------------------------------------------------------------------- */
/* Local UI store                                                             */
/* -------------------------------------------------------------------------- */

export type ViewMode = "grid" | "list";

interface NotesUiState {
  viewMode: ViewMode;
  sortOrder: SortOrder;
  activeFolderId: Id | null;
  activeTagId: Id | null;
  favoritesOnly: boolean;
  setViewMode: (mode: ViewMode) => void;
  toggleViewMode: () => void;
  setSortOrder: (sort: SortOrder) => void;
  setActiveFolderId: (id: Id | null) => void;
  setActiveTagId: (id: Id | null) => void;
  setFavoritesOnly: (value: boolean) => void;
  resetFilters: () => void;
}

/**
 * Local presentation state only — the backend remains the source of truth for
 * notes, folders, tags and settings.
 */
export const useNotesUiStore = create<NotesUiState>()(
  persist(
    (set) => ({
      viewMode: "grid",
      sortOrder: "newest",
      activeFolderId: null,
      activeTagId: null,
      favoritesOnly: false,
      setViewMode: (viewMode) => set({ viewMode }),
      toggleViewMode: () =>
        set((state) => ({
          viewMode: state.viewMode === "grid" ? "list" : "grid",
        })),
      setSortOrder: (sortOrder) => set({ sortOrder }),
      setActiveFolderId: (activeFolderId) => set({ activeFolderId }),
      setActiveTagId: (activeTagId) => set({ activeTagId }),
      setFavoritesOnly: (favoritesOnly) => set({ favoritesOnly }),
      resetFilters: () =>
        set({ activeFolderId: null, activeTagId: null, favoritesOnly: false }),
    }),
    { name: "nexa-notes-ui" },
  ),
);

/* -------------------------------------------------------------------------- */
/* Actor access                                                               */
/* -------------------------------------------------------------------------- */

/**
 * The generated bindings currently expose only the authorization surface; the
 * notes mixin is regenerated by `pnpm bindgen`. Casting through the shared
 * `NotesBackend` interface keeps the UI typed against the backend contract.
 */
export function useNotesActor(): {
  notes: NotesBackend | null;
  isFetching: boolean;
} {
  const { actor, isFetching } = useActor(createActor);
  return {
    notes: (actor as unknown as NotesBackend | null) ?? null,
    isFetching,
  };
}

/* -------------------------------------------------------------------------- */
/* Query keys                                                                 */
/* -------------------------------------------------------------------------- */

/**
 * React Query hashes keys with `JSON.stringify`, which throws on `bigint`.
 * Normalize the filter's bigint ids to strings for the key only — the filter
 * handed to the backend keeps its original bigint values.
 */
function serializeFilter(filter: NoteFilter) {
  return {
    folderId: filter.folderId === null ? null : filter.folderId.toString(),
    tagId: filter.tagId === null ? null : filter.tagId.toString(),
    favoritesOnly: filter.favoritesOnly,
    includeTrashed: filter.includeTrashed,
  };
}

export const notesKeys = {
  all: ["notes"] as const,
  list: (sort: SortOrder, filter: NoteFilter) =>
    ["notes", "list", sort, serializeFilter(filter)] as const,
  detail: (id: Id) => ["notes", "detail", id.toString()] as const,
  search: (term: string) => ["notes", "search", term] as const,
  folders: ["folders"] as const,
  tags: ["tags"] as const,
  settings: ["settings"] as const,
};

/* -------------------------------------------------------------------------- */
/* Queries                                                                    */
/* -------------------------------------------------------------------------- */

export function useNotes(
  sort: SortOrder,
  filter: NoteFilter = DEFAULT_NOTE_FILTER,
) {
  const { notes, isFetching } = useNotesActor();
  return useQuery({
    queryKey: notesKeys.list(sort, filter),
    queryFn: async () => {
      if (!notes) return [];
      return notes.listNotes(sort, filter);
    },
    enabled: !!notes && !isFetching,
  });
}

export function useNote(id: Id | null) {
  const { notes, isFetching } = useNotesActor();
  return useQuery({
    queryKey: notesKeys.detail(id ?? 0n),
    queryFn: async () => {
      if (!notes || id === null) return null;
      // The backend's listNotes keeps a note only when
      // `note.trashed == filter.includeTrashed`, so a single call can never
      // return both active and trashed notes. Query each list and look the id
      // up in either.
      const [active, trashed] = await Promise.all([
        notes.listNotes("newest", {
          ...DEFAULT_NOTE_FILTER,
          includeTrashed: false,
        }),
        notes.listNotes("newest", {
          ...DEFAULT_NOTE_FILTER,
          includeTrashed: true,
        }),
      ]);
      return (
        active.find((note) => note.id === id) ??
        trashed.find((note) => note.id === id) ??
        null
      );
    },
    enabled: !!notes && !isFetching && id !== null,
  });
}

export function useSearchNotes(term: string) {
  const { notes, isFetching } = useNotesActor();
  const trimmed = term.trim();
  return useQuery({
    queryKey: notesKeys.search(trimmed),
    queryFn: async () => {
      if (!notes) return [];
      return notes.searchNotes(trimmed);
    },
    enabled: !!notes && !isFetching && trimmed.length > 0,
  });
}

export function useFolders() {
  const { notes, isFetching } = useNotesActor();
  return useQuery({
    queryKey: notesKeys.folders,
    queryFn: async () => {
      if (!notes) return [] as Folder[];
      return notes.listFolders();
    },
    enabled: !!notes && !isFetching,
  });
}

export function useTags() {
  const { notes, isFetching } = useNotesActor();
  return useQuery({
    queryKey: notesKeys.tags,
    queryFn: async () => {
      if (!notes) return [] as Tag[];
      return notes.listTags();
    },
    enabled: !!notes && !isFetching,
  });
}

export function useSettings() {
  const { notes, isFetching } = useNotesActor();
  return useQuery({
    queryKey: notesKeys.settings,
    queryFn: async () => {
      if (!notes) return DEFAULT_SETTINGS;
      return notes.getSettings();
    },
    enabled: !!notes && !isFetching,
  });
}

/* -------------------------------------------------------------------------- */
/* Mutations                                                                  */
/* -------------------------------------------------------------------------- */

function useInvalidateNotes() {
  const queryClient = useQueryClient();
  return () => {
    void queryClient.invalidateQueries({ queryKey: notesKeys.all });
  };
}

export function useCreateNote() {
  const { notes } = useNotesActor();
  const invalidate = useInvalidateNotes();
  return useMutation({
    mutationFn: async (input: NoteInput) => {
      if (!notes) throw new Error("Backend is not ready");
      return notes.createNote(input);
    },
    onSuccess: () => {
      invalidate();
    },
  });
}

export function useUpdateNote() {
  const { notes } = useNotesActor();
  const invalidate = useInvalidateNotes();
  return useMutation({
    mutationFn: async ({ id, patch }: { id: Id; patch: NotePatch }) => {
      if (!notes) throw new Error("Backend is not ready");
      return notes.updateNote(id, patch);
    },
    onSuccess: () => {
      invalidate();
    },
  });
}

export function useDuplicateNote() {
  const { notes } = useNotesActor();
  const invalidate = useInvalidateNotes();
  return useMutation({
    mutationFn: async (id: Id) => {
      if (!notes) throw new Error("Backend is not ready");
      return notes.duplicateNote(id);
    },
    onSuccess: () => {
      invalidate();
    },
  });
}

export function useTrashNote() {
  const { notes } = useNotesActor();
  const invalidate = useInvalidateNotes();
  return useMutation({
    mutationFn: async (id: Id) => {
      if (!notes) throw new Error("Backend is not ready");
      return notes.trashNote(id);
    },
    onSuccess: () => {
      invalidate();
    },
  });
}

export function useRestoreNote() {
  const { notes } = useNotesActor();
  const invalidate = useInvalidateNotes();
  return useMutation({
    mutationFn: async (id: Id) => {
      if (!notes) throw new Error("Backend is not ready");
      return notes.restoreNote(id);
    },
    onSuccess: () => {
      invalidate();
    },
  });
}

export function useDeleteNotePermanently() {
  const { notes } = useNotesActor();
  const invalidate = useInvalidateNotes();
  return useMutation({
    mutationFn: async (id: Id) => {
      if (!notes) throw new Error("Backend is not ready");
      return notes.deleteNotePermanently(id);
    },
    onSuccess: () => {
      invalidate();
    },
  });
}

export function useSetPinned() {
  const { notes } = useNotesActor();
  const invalidate = useInvalidateNotes();
  return useMutation({
    mutationFn: async ({ id, pinned }: { id: Id; pinned: boolean }) => {
      if (!notes) throw new Error("Backend is not ready");
      return notes.setPinned(id, pinned);
    },
    onSuccess: () => {
      invalidate();
    },
  });
}

export function useSetFavorite() {
  const { notes } = useNotesActor();
  const invalidate = useInvalidateNotes();
  return useMutation({
    mutationFn: async ({ id, favorite }: { id: Id; favorite: boolean }) => {
      if (!notes) throw new Error("Backend is not ready");
      return notes.setFavorite(id, favorite);
    },
    onSuccess: () => {
      invalidate();
    },
  });
}

export function useToggleChecklistItem() {
  const { notes } = useNotesActor();
  const invalidate = useInvalidateNotes();
  return useMutation({
    mutationFn: async ({ noteId, itemId }: { noteId: Id; itemId: Id }) => {
      if (!notes) throw new Error("Backend is not ready");
      return notes.toggleChecklistItem(noteId, itemId);
    },
    onSuccess: () => {
      invalidate();
    },
  });
}

export function useCreateFolder() {
  const { notes } = useNotesActor();
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: async (name: string) => {
      if (!notes) throw new Error("Backend is not ready");
      return notes.createFolder(name);
    },
    onSuccess: () => {
      void queryClient.invalidateQueries({ queryKey: notesKeys.folders });
    },
  });
}

export function useRenameFolder() {
  const { notes } = useNotesActor();
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: async ({ id, name }: { id: Id; name: string }) => {
      if (!notes) throw new Error("Backend is not ready");
      return notes.renameFolder(id, name);
    },
    onSuccess: () => {
      void queryClient.invalidateQueries({ queryKey: notesKeys.folders });
    },
  });
}

export function useDeleteFolder() {
  const { notes } = useNotesActor();
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: async (id: Id) => {
      if (!notes) throw new Error("Backend is not ready");
      return notes.deleteFolder(id);
    },
    onSuccess: () => {
      void queryClient.invalidateQueries({ queryKey: notesKeys.folders });
      void queryClient.invalidateQueries({ queryKey: notesKeys.all });
    },
  });
}

export function useCreateTag() {
  const { notes } = useNotesActor();
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: async (name: string) => {
      if (!notes) throw new Error("Backend is not ready");
      return notes.createTag(name);
    },
    onSuccess: () => {
      void queryClient.invalidateQueries({ queryKey: notesKeys.tags });
    },
  });
}

export function useDeleteTag() {
  const { notes } = useNotesActor();
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: async (id: Id) => {
      if (!notes) throw new Error("Backend is not ready");
      return notes.deleteTag(id);
    },
    onSuccess: () => {
      void queryClient.invalidateQueries({ queryKey: notesKeys.tags });
      void queryClient.invalidateQueries({ queryKey: notesKeys.all });
    },
  });
}

export function useUpdateSettings() {
  const { notes } = useNotesActor();
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: async (settings: Settings) => {
      if (!notes) throw new Error("Backend is not ready");
      return notes.updateSettings(settings);
    },
    onSuccess: () => {
      void queryClient.invalidateQueries({ queryKey: notesKeys.settings });
    },
  });
}

export function useSeedSampleNotes() {
  const { notes } = useNotesActor();
  const invalidate = useInvalidateNotes();
  return useMutation({
    mutationFn: async () => {
      if (!notes) throw new Error("Backend is not ready");
      return notes.seedSampleNotes();
    },
    onSuccess: () => {
      invalidate();
    },
  });
}
