/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Cell { 'value' : Value, 'name' : string }
export interface ChecklistItem {
  'id' : Id,
  'text' : string,
  'completed' : boolean,
}
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export interface Folder { 'id' : Id, 'name' : string, 'createdAt' : Timestamp }
export type Id = bigint;
export interface Note {
  'id' : Id,
  'title' : string,
  'body' : RichText,
  'createdAt' : Timestamp,
  'tagIds' : Array<Id>,
  'updatedAt' : Timestamp,
  'pinned' : boolean,
  'trashed' : boolean,
  'checklist' : Array<ChecklistItem>,
  'folderId' : [] | [Id],
  'favorite' : boolean,
}
export interface NoteFilter {
  'tagId' : [] | [Id],
  'favoritesOnly' : boolean,
  'includeTrashed' : boolean,
  'folderId' : [] | [Id],
}
export interface NoteInput {
  'title' : string,
  'body' : RichText,
  'tagIds' : Array<Id>,
  'checklist' : Array<ChecklistItem>,
  'folderId' : [] | [Id],
}
export interface NotePatch {
  'title' : [] | [string],
  'body' : [] | [RichText],
  'tagIds' : [] | [Array<Id>],
  'clearFolder' : [] | [boolean],
  'checklist' : [] | [Array<ChecklistItem>],
  'clearBody' : [] | [boolean],
  'folderId' : [] | [Id],
  'clearTitle' : [] | [boolean],
}
export interface Result { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export type Result__1 = { 'ok' : null } |
  { 'err' : Error };
export type RichText = string;
export interface Settings {
  'theme' : Theme,
  'sortOrder' : SortOrder,
  'gridView' : boolean,
}
export type SortOrder = { 'title' : null } |
  { 'favorites' : null } |
  { 'newest' : null } |
  { 'oldest' : null };
export interface Tag { 'id' : Id, 'name' : string, 'createdAt' : Timestamp }
export type Theme = { 'dark' : null } |
  { 'automatic' : null } |
  { 'light' : null };
export type Timestamp = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface _SERVICE {
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result__1>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  /**
   * / Create a folder.
   */
  'createFolder' : ActorMethod<[string], Folder>,
  /**
   * / Create a new note for the caller.
   */
  'createNote' : ActorMethod<[NoteInput], Note>,
  /**
   * / Create a tag.
   */
  'createTag' : ActorMethod<[string], Tag>,
  /**
   * / Delete a folder.
   */
  'deleteFolder' : ActorMethod<[Id], boolean>,
  /**
   * / Permanently delete a note.
   */
  'deleteNotePermanently' : ActorMethod<[Id], boolean>,
  /**
   * / Delete a tag.
   */
  'deleteTag' : ActorMethod<[Id], boolean>,
  /**
   * / Duplicate a note into an independent copy.
   */
  'duplicateNote' : ActorMethod<[Id], [] | [Note]>,
  'execute' : ActorMethod<[string], Result>,
  /**
   * / Return the backend's API documentation as Markdown.
   */
  'getApiDoc' : ActorMethod<[], string>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  /**
   * / Read the caller's settings.
   */
  'getSettings' : ActorMethod<[], Settings>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  /**
   * / List the caller's folders.
   */
  'listFolders' : ActorMethod<[], Array<Folder>>,
  /**
   * / List the caller's notes with sort and filters.
   */
  'listNotes' : ActorMethod<[SortOrder, NoteFilter], Array<Note>>,
  /**
   * / List the caller's tags.
   */
  'listTags' : ActorMethod<[], Array<Tag>>,
  /**
   * / Rename a folder.
   */
  'renameFolder' : ActorMethod<[Id, string], [] | [Folder]>,
  /**
   * / Restore a note from trash.
   */
  'restoreNote' : ActorMethod<[Id], [] | [Note]>,
  'schema' : ActorMethod<[], string>,
  /**
   * / Search the caller's notes across title, body and tags.
   */
  'searchNotes' : ActorMethod<[string], Array<Note>>,
  /**
   * / Seed sample notes for the caller on first launch.
   */
  'seedSampleNotes' : ActorMethod<[], Array<Note>>,
  /**
   * / Mark or unmark a note as favorite.
   */
  'setFavorite' : ActorMethod<[Id, boolean], [] | [Note]>,
  /**
   * / Pin or unpin a note.
   */
  'setPinned' : ActorMethod<[Id, boolean], [] | [Note]>,
  /**
   * / Toggle a checklist item inside a note.
   */
  'toggleChecklistItem' : ActorMethod<[Id, Id], [] | [Note]>,
  /**
   * / Move a note to trash.
   */
  'trashNote' : ActorMethod<[Id], boolean>,
  /**
   * / Apply a partial update (autosave) to a note.
   */
  'updateNote' : ActorMethod<[Id, NotePatch], [] | [Note]>,
  /**
   * / Persist the caller's settings.
   */
  'updateSettings' : ActorMethod<[Settings], Settings>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];