/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Id = IDL.Nat;
export const Timestamp = IDL.Int;
export const Folder = IDL.Record({
  'id' : Id,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
});
export const RichText = IDL.Text;
export const ChecklistItem = IDL.Record({
  'id' : Id,
  'text' : IDL.Text,
  'completed' : IDL.Bool,
});
export const NoteInput = IDL.Record({
  'title' : IDL.Text,
  'body' : RichText,
  'tagIds' : IDL.Vec(Id),
  'checklist' : IDL.Vec(ChecklistItem),
  'folderId' : IDL.Opt(Id),
});
export const Note = IDL.Record({
  'id' : Id,
  'title' : IDL.Text,
  'body' : RichText,
  'createdAt' : Timestamp,
  'tagIds' : IDL.Vec(Id),
  'updatedAt' : Timestamp,
  'pinned' : IDL.Bool,
  'trashed' : IDL.Bool,
  'checklist' : IDL.Vec(ChecklistItem),
  'folderId' : IDL.Opt(Id),
  'favorite' : IDL.Bool,
});
export const Tag = IDL.Record({
  'id' : Id,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
});
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const Theme = IDL.Variant({
  'dark' : IDL.Null,
  'automatic' : IDL.Null,
  'light' : IDL.Null,
});
export const SortOrder = IDL.Variant({
  'title' : IDL.Null,
  'favorites' : IDL.Null,
  'newest' : IDL.Null,
  'oldest' : IDL.Null,
});
export const Settings = IDL.Record({
  'theme' : Theme,
  'sortOrder' : SortOrder,
  'gridView' : IDL.Bool,
});
export const NoteFilter = IDL.Record({
  'tagId' : IDL.Opt(Id),
  'favoritesOnly' : IDL.Bool,
  'includeTrashed' : IDL.Bool,
  'folderId' : IDL.Opt(Id),
});
export const NotePatch = IDL.Record({
  'title' : IDL.Opt(IDL.Text),
  'body' : IDL.Opt(RichText),
  'tagIds' : IDL.Opt(IDL.Vec(Id)),
  'clearFolder' : IDL.Opt(IDL.Bool),
  'checklist' : IDL.Opt(IDL.Vec(ChecklistItem)),
  'clearBody' : IDL.Opt(IDL.Bool),
  'folderId' : IDL.Opt(Id),
  'clearTitle' : IDL.Opt(IDL.Bool),
});

export const idlService = IDL.Service({
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createFolder' : IDL.Func([IDL.Text], [Folder], []),
  'createNote' : IDL.Func([NoteInput], [Note], []),
  'createTag' : IDL.Func([IDL.Text], [Tag], []),
  'deleteFolder' : IDL.Func([Id], [IDL.Bool], []),
  'deleteNotePermanently' : IDL.Func([Id], [IDL.Bool], []),
  'deleteTag' : IDL.Func([Id], [IDL.Bool], []),
  'duplicateNote' : IDL.Func([Id], [IDL.Opt(Note)], []),
  'execute' : IDL.Func([IDL.Text], [Result], ['query']),
  'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getSettings' : IDL.Func([], [Settings], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listFolders' : IDL.Func([], [IDL.Vec(Folder)], ['query']),
  'listNotes' : IDL.Func([SortOrder, NoteFilter], [IDL.Vec(Note)], ['query']),
  'listTags' : IDL.Func([], [IDL.Vec(Tag)], ['query']),
  'renameFolder' : IDL.Func([Id, IDL.Text], [IDL.Opt(Folder)], []),
  'restoreNote' : IDL.Func([Id], [IDL.Opt(Note)], []),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'searchNotes' : IDL.Func([IDL.Text], [IDL.Vec(Note)], ['query']),
  'seedSampleNotes' : IDL.Func([], [IDL.Vec(Note)], []),
  'setFavorite' : IDL.Func([Id, IDL.Bool], [IDL.Opt(Note)], []),
  'setPinned' : IDL.Func([Id, IDL.Bool], [IDL.Opt(Note)], []),
  'toggleChecklistItem' : IDL.Func([Id, Id], [IDL.Opt(Note)], []),
  'trashNote' : IDL.Func([Id], [IDL.Bool], []),
  'updateNote' : IDL.Func([Id, NotePatch], [IDL.Opt(Note)], []),
  'updateSettings' : IDL.Func([Settings], [Settings], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Id = IDL.Nat;
  const Timestamp = IDL.Int;
  const Folder = IDL.Record({
    'id' : Id,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
  });
  const RichText = IDL.Text;
  const ChecklistItem = IDL.Record({
    'id' : Id,
    'text' : IDL.Text,
    'completed' : IDL.Bool,
  });
  const NoteInput = IDL.Record({
    'title' : IDL.Text,
    'body' : RichText,
    'tagIds' : IDL.Vec(Id),
    'checklist' : IDL.Vec(ChecklistItem),
    'folderId' : IDL.Opt(Id),
  });
  const Note = IDL.Record({
    'id' : Id,
    'title' : IDL.Text,
    'body' : RichText,
    'createdAt' : Timestamp,
    'tagIds' : IDL.Vec(Id),
    'updatedAt' : Timestamp,
    'pinned' : IDL.Bool,
    'trashed' : IDL.Bool,
    'checklist' : IDL.Vec(ChecklistItem),
    'folderId' : IDL.Opt(Id),
    'favorite' : IDL.Bool,
  });
  const Tag = IDL.Record({
    'id' : Id,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
  });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const Theme = IDL.Variant({
    'dark' : IDL.Null,
    'automatic' : IDL.Null,
    'light' : IDL.Null,
  });
  const SortOrder = IDL.Variant({
    'title' : IDL.Null,
    'favorites' : IDL.Null,
    'newest' : IDL.Null,
    'oldest' : IDL.Null,
  });
  const Settings = IDL.Record({
    'theme' : Theme,
    'sortOrder' : SortOrder,
    'gridView' : IDL.Bool,
  });
  const NoteFilter = IDL.Record({
    'tagId' : IDL.Opt(Id),
    'favoritesOnly' : IDL.Bool,
    'includeTrashed' : IDL.Bool,
    'folderId' : IDL.Opt(Id),
  });
  const NotePatch = IDL.Record({
    'title' : IDL.Opt(IDL.Text),
    'body' : IDL.Opt(RichText),
    'tagIds' : IDL.Opt(IDL.Vec(Id)),
    'clearFolder' : IDL.Opt(IDL.Bool),
    'checklist' : IDL.Opt(IDL.Vec(ChecklistItem)),
    'clearBody' : IDL.Opt(IDL.Bool),
    'folderId' : IDL.Opt(Id),
    'clearTitle' : IDL.Opt(IDL.Bool),
  });
  
  return IDL.Service({
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createFolder' : IDL.Func([IDL.Text], [Folder], []),
    'createNote' : IDL.Func([NoteInput], [Note], []),
    'createTag' : IDL.Func([IDL.Text], [Tag], []),
    'deleteFolder' : IDL.Func([Id], [IDL.Bool], []),
    'deleteNotePermanently' : IDL.Func([Id], [IDL.Bool], []),
    'deleteTag' : IDL.Func([Id], [IDL.Bool], []),
    'duplicateNote' : IDL.Func([Id], [IDL.Opt(Note)], []),
    'execute' : IDL.Func([IDL.Text], [Result], ['query']),
    'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getSettings' : IDL.Func([], [Settings], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listFolders' : IDL.Func([], [IDL.Vec(Folder)], ['query']),
    'listNotes' : IDL.Func([SortOrder, NoteFilter], [IDL.Vec(Note)], ['query']),
    'listTags' : IDL.Func([], [IDL.Vec(Tag)], ['query']),
    'renameFolder' : IDL.Func([Id, IDL.Text], [IDL.Opt(Folder)], []),
    'restoreNote' : IDL.Func([Id], [IDL.Opt(Note)], []),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'searchNotes' : IDL.Func([IDL.Text], [IDL.Vec(Note)], ['query']),
    'seedSampleNotes' : IDL.Func([], [IDL.Vec(Note)], []),
    'setFavorite' : IDL.Func([Id, IDL.Bool], [IDL.Opt(Note)], []),
    'setPinned' : IDL.Func([Id, IDL.Bool], [IDL.Opt(Note)], []),
    'toggleChecklistItem' : IDL.Func([Id, Id], [IDL.Opt(Note)], []),
    'trashNote' : IDL.Func([Id], [IDL.Bool], []),
    'updateNote' : IDL.Func([Id, NotePatch], [IDL.Opt(Note)], []),
    'updateSettings' : IDL.Func([Settings], [Settings], []),
  });
};

export const init = ({ IDL }) => { return []; };