/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
import { ExternalBlob } from "@caffeineai/object-storage";
export { ExternalBlob } from "@caffeineai/object-storage";
export interface Cell {
    value: Value;
    name: string;
}
export interface ChecklistItem {
    id: Id;
    text: string;
    completed: boolean;
}
export type Error_ = {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
};
export interface Folder {
    id: Id;
    name: string;
    createdAt: Timestamp;
}
export type Id = bigint;
export interface Note {
    id: Id;
    title: string;
    body: RichText;
    createdAt: Timestamp;
    tagIds: Array<Id>;
    updatedAt: Timestamp;
    pinned: boolean;
    trashed: boolean;
    checklist: Array<ChecklistItem>;
    folderId?: Id;
    favorite: boolean;
}
export interface NoteFilter {
    tagId?: Id;
    favoritesOnly: boolean;
    includeTrashed: boolean;
    folderId?: Id;
}
export interface NoteInput {
    title: string;
    body: RichText;
    tagIds: Array<Id>;
    checklist: Array<ChecklistItem>;
    folderId?: Id;
}
export interface NotePatch {
    title?: string;
    body?: RichText;
    tagIds?: Array<Id>;
    clearFolder?: boolean;
    checklist?: Array<ChecklistItem>;
    clearBody?: boolean;
    folderId?: Id;
    clearTitle?: boolean;
}
export interface Result {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
}
export type Result__1 = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
};
export type RichText = string;
export interface Settings {
    theme: Theme;
    sortOrder: SortOrder;
    gridView: boolean;
}
export interface Tag {
    id: Id;
    name: string;
    createdAt: Timestamp;
}
export type Timestamp = bigint;
export type Value = {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
};
export enum SortOrder {
    title = "title",
    favorites = "favorites",
    newest = "newest",
    oldest = "oldest"
}
export enum Theme {
    dark = "dark",
    automatic = "automatic",
    light = "light"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initialize_access_control(): Promise<void>;
    _internet_identity_sign_in_finish(): Promise<Result__1>;
    _internet_identity_sign_in_start(): Promise<Uint8Array>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    /**
     * / Create a folder.
     */
    createFolder(name: string): Promise<Folder>;
    /**
     * / Create a new note for the caller.
     */
    createNote(input: NoteInput): Promise<Note>;
    /**
     * / Create a tag.
     */
    createTag(name: string): Promise<Tag>;
    /**
     * / Delete a folder.
     */
    deleteFolder(id: Id): Promise<boolean>;
    /**
     * / Permanently delete a note.
     */
    deleteNotePermanently(id: Id): Promise<boolean>;
    /**
     * / Delete a tag.
     */
    deleteTag(id: Id): Promise<boolean>;
    /**
     * / Duplicate a note into an independent copy.
     */
    duplicateNote(id: Id): Promise<Note | null>;
    execute(qJson: string): Promise<Result>;
    /**
     * / Return the backend's API documentation as Markdown.
     */
    getApiDoc(): Promise<string>;
    getCallerUserRole(): Promise<UserRole>;
    /**
     * / Read the caller's settings.
     */
    getSettings(): Promise<Settings>;
    isCallerAdmin(): Promise<boolean>;
    /**
     * / List the caller's folders.
     */
    listFolders(): Promise<Array<Folder>>;
    /**
     * / List the caller's notes with sort and filters.
     */
    listNotes(sort: SortOrder, filter: NoteFilter): Promise<Array<Note>>;
    /**
     * / List the caller's tags.
     */
    listTags(): Promise<Array<Tag>>;
    /**
     * / Rename a folder.
     */
    renameFolder(id: Id, name: string): Promise<Folder | null>;
    /**
     * / Restore a note from trash.
     */
    restoreNote(id: Id): Promise<Note | null>;
    schema(): Promise<string>;
    /**
     * / Search the caller's notes across title, body and tags.
     */
    searchNotes(term: string): Promise<Array<Note>>;
    /**
     * / Seed sample notes for the caller on first launch.
     */
    seedSampleNotes(): Promise<Array<Note>>;
    /**
     * / Mark or unmark a note as favorite.
     */
    setFavorite(id: Id, favorite: boolean): Promise<Note | null>;
    /**
     * / Pin or unpin a note.
     */
    setPinned(id: Id, pinned: boolean): Promise<Note | null>;
    /**
     * / Toggle a checklist item inside a note.
     */
    toggleChecklistItem(noteId: Id, itemId: Id): Promise<Note | null>;
    /**
     * / Move a note to trash.
     */
    trashNote(id: Id): Promise<boolean>;
    /**
     * / Apply a partial update (autosave) to a note.
     */
    updateNote(id: Id, patch: NotePatch): Promise<Note | null>;
    /**
     * / Persist the caller's settings.
     */
    updateSettings(settings: Settings): Promise<Settings>;
}
import type { Cell as _Cell, ChecklistItem as _ChecklistItem, Error as _Error, Folder as _Folder, Id as _Id, Note as _Note, NoteFilter as _NoteFilter, NoteInput as _NoteInput, NotePatch as _NotePatch, Result as _Result, Result__1 as _Result__1, RichText as _RichText, Settings as _Settings, SortOrder as _SortOrder, Theme as _Theme, Timestamp as _Timestamp, UserRole as _UserRole, Value as _Value } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initialize_access_control(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initialize_access_control();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initialize_access_control();
            return result;
        }
    }
    async _internet_identity_sign_in_finish(): Promise<Result__1> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_finish();
                return from_candid_Result__1_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_finish();
            return from_candid_Result__1_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async _internet_identity_sign_in_start(): Promise<Uint8Array> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_start();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_start();
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createFolder(arg0: string): Promise<Folder> {
        if (this.processError) {
            try {
                const result = await this.actor.createFolder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createFolder(arg0);
            return result;
        }
    }
    async createNote(arg0: NoteInput): Promise<Note> {
        if (this.processError) {
            try {
                const result = await this.actor.createNote(to_candid_NoteInput_n6(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Note_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createNote(to_candid_NoteInput_n6(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Note_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async createTag(arg0: string): Promise<Tag> {
        if (this.processError) {
            try {
                const result = await this.actor.createTag(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTag(arg0);
            return result;
        }
    }
    async deleteFolder(arg0: Id): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteFolder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteFolder(arg0);
            return result;
        }
    }
    async deleteNotePermanently(arg0: Id): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteNotePermanently(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteNotePermanently(arg0);
            return result;
        }
    }
    async deleteTag(arg0: Id): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTag(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTag(arg0);
            return result;
        }
    }
    async duplicateNote(arg0: Id): Promise<Note | null> {
        if (this.processError) {
            try {
                const result = await this.actor.duplicateNote(arg0);
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.duplicateNote(arg0);
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async execute(arg0: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.execute(arg0);
                return from_candid_Result_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.execute(arg0);
            return from_candid_Result_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getApiDoc(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getApiDoc();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApiDoc();
            return result;
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSettings(): Promise<Settings> {
        if (this.processError) {
            try {
                const result = await this.actor.getSettings();
                return from_candid_Settings_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSettings();
            return from_candid_Settings_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listFolders(): Promise<Array<Folder>> {
        if (this.processError) {
            try {
                const result = await this.actor.listFolders();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listFolders();
            return result;
        }
    }
    async listNotes(arg0: SortOrder, arg1: NoteFilter): Promise<Array<Note>> {
        if (this.processError) {
            try {
                const result = await this.actor.listNotes(to_candid_SortOrder_n25(this._uploadFile, this._downloadFile, arg0), to_candid_NoteFilter_n26(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listNotes(to_candid_SortOrder_n25(this._uploadFile, this._downloadFile, arg0), to_candid_NoteFilter_n26(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async listTags(): Promise<Array<Tag>> {
        if (this.processError) {
            try {
                const result = await this.actor.listTags();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listTags();
            return result;
        }
    }
    async renameFolder(arg0: Id, arg1: string): Promise<Folder | null> {
        if (this.processError) {
            try {
                const result = await this.actor.renameFolder(arg0, arg1);
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.renameFolder(arg0, arg1);
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async restoreNote(arg0: Id): Promise<Note | null> {
        if (this.processError) {
            try {
                const result = await this.actor.restoreNote(arg0);
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.restoreNote(arg0);
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async schema(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.schema();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.schema();
            return result;
        }
    }
    async searchNotes(arg0: string): Promise<Array<Note>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchNotes(arg0);
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchNotes(arg0);
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async seedSampleNotes(): Promise<Array<Note>> {
        if (this.processError) {
            try {
                const result = await this.actor.seedSampleNotes();
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.seedSampleNotes();
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async setFavorite(arg0: Id, arg1: boolean): Promise<Note | null> {
        if (this.processError) {
            try {
                const result = await this.actor.setFavorite(arg0, arg1);
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setFavorite(arg0, arg1);
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async setPinned(arg0: Id, arg1: boolean): Promise<Note | null> {
        if (this.processError) {
            try {
                const result = await this.actor.setPinned(arg0, arg1);
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setPinned(arg0, arg1);
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async toggleChecklistItem(arg0: Id, arg1: Id): Promise<Note | null> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleChecklistItem(arg0, arg1);
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleChecklistItem(arg0, arg1);
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async trashNote(arg0: Id): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.trashNote(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.trashNote(arg0);
            return result;
        }
    }
    async updateNote(arg0: Id, arg1: NotePatch): Promise<Note | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateNote(arg0, to_candid_NotePatch_n30(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateNote(arg0, to_candid_NotePatch_n30(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateSettings(arg0: Settings): Promise<Settings> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSettings(to_candid_Settings_n32(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Settings_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSettings(to_candid_Settings_n32(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Settings_n21(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_Cell_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Cell): Cell {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_Error_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Error): Error_ {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_Note_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Note): Note {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_Result__1_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result__1): Result__1 {
    return from_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_Settings_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Settings): Settings {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_SortOrder_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SortOrder): SortOrder {
    return "title" in value ? SortOrder.title : "favorites" in value ? SortOrder.favorites : "newest" in value ? SortOrder.newest : "oldest" in value ? SortOrder.oldest : value;
}
function from_candid_Theme_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Theme): Theme {
    return "dark" in value ? Theme.dark : "automatic" in value ? Theme.automatic : "light" in value ? Theme.light : value;
}
function from_candid_UserRole_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_Value_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Value): Value {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Id]): Id | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Note]): Note | null {
    return value.length === 0 ? null : from_candid_Note_n8(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Folder]): Folder | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hasMore: boolean;
    rows: Array<Array<_Cell>>;
}): {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
} {
    return {
        hasMore: value.hasMore,
        rows: from_candid_vec_n14(_uploadFile, _downloadFile, value.rows)
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    value: _Value;
    name: string;
}): {
    value: Value;
    name: string;
} {
    return {
        value: from_candid_Value_n18(_uploadFile, _downloadFile, value.value),
        name: value.name
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    theme: _Theme;
    sortOrder: _SortOrder;
    gridView: boolean;
}): {
    theme: Theme;
    sortOrder: SortOrder;
    gridView: boolean;
} {
    return {
        theme: from_candid_Theme_n23(_uploadFile, _downloadFile, value.theme),
        sortOrder: from_candid_SortOrder_n24(_uploadFile, _downloadFile, value.sortOrder),
        gridView: value.gridView
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _Id;
    title: string;
    body: _RichText;
    createdAt: _Timestamp;
    tagIds: Array<_Id>;
    updatedAt: _Timestamp;
    pinned: boolean;
    trashed: boolean;
    checklist: Array<_ChecklistItem>;
    folderId: [] | [_Id];
    favorite: boolean;
}): {
    id: Id;
    title: string;
    body: RichText;
    createdAt: Timestamp;
    tagIds: Array<Id>;
    updatedAt: Timestamp;
    pinned: boolean;
    trashed: boolean;
    checklist: Array<ChecklistItem>;
    folderId?: Id;
    favorite: boolean;
} {
    return {
        id: value.id,
        title: value.title,
        body: value.body,
        createdAt: value.createdAt,
        tagIds: value.tagIds,
        updatedAt: value.updatedAt,
        pinned: value.pinned,
        trashed: value.trashed,
        checklist: value.checklist,
        folderId: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.folderId)),
        favorite: value.favorite
    };
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    int: bigint;
} | {
    nat: bigint;
} | {
    float: number;
} | {
    bool: boolean;
} | {
    null: null;
} | {
    text: string;
}): {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
} {
    return "int" in value ? {
        __kind__: "int",
        int: value.int
    } : "nat" in value ? {
        __kind__: "nat",
        nat: value.nat
    } : "float" in value ? {
        __kind__: "float",
        float: value.float
    } : "bool" in value ? {
        __kind__: "bool",
        bool: value.bool
    } : "null" in value ? {
        __kind__: "null",
        null: value.null
    } : "text" in value ? {
        __kind__: "text",
        text: value.text
    } : value;
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: _Error;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_Error_n3(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    FrontendOriginsNotConfigured: null;
} | {
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    Stale: {
        ageNs: bigint;
    };
} | {
    MalformedCandid: null;
} | {
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    NoAttributes: null;
} | {
    UnknownNonce: null;
} | {
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    MissingField: string;
} | {
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
}): {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
} {
    return "FrontendOriginsNotConfigured" in value ? {
        __kind__: "FrontendOriginsNotConfigured",
        FrontendOriginsNotConfigured: value.FrontendOriginsNotConfigured
    } : "MixedSsoSources" in value ? {
        __kind__: "MixedSsoSources",
        MixedSsoSources: value.MixedSsoSources
    } : "Stale" in value ? {
        __kind__: "Stale",
        Stale: value.Stale
    } : "MalformedCandid" in value ? {
        __kind__: "MalformedCandid",
        MalformedCandid: value.MalformedCandid
    } : "AmbiguousAttribute" in value ? {
        __kind__: "AmbiguousAttribute",
        AmbiguousAttribute: value.AmbiguousAttribute
    } : "NoAttributes" in value ? {
        __kind__: "NoAttributes",
        NoAttributes: value.NoAttributes
    } : "UnknownNonce" in value ? {
        __kind__: "UnknownNonce",
        UnknownNonce: value.UnknownNonce
    } : "UntrustedSsoSource" in value ? {
        __kind__: "UntrustedSsoSource",
        UntrustedSsoSource: value.UntrustedSsoSource
    } : "MissingField" in value ? {
        __kind__: "MissingField",
        MissingField: value.MissingField
    } : "FrontendOriginMismatch" in value ? {
        __kind__: "FrontendOriginMismatch",
        FrontendOriginMismatch: value.FrontendOriginMismatch
    } : value;
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Array<_Cell>>): Array<Array<Cell>> {
    return value.map((x)=>from_candid_vec_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Cell>): Array<Cell> {
    return value.map((x)=>from_candid_Cell_n16(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Note>): Array<Note> {
    return value.map((x)=>from_candid_Note_n8(_uploadFile, _downloadFile, x));
}
function to_candid_NoteFilter_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NoteFilter): _NoteFilter {
    return to_candid_record_n27(_uploadFile, _downloadFile, value);
}
function to_candid_NoteInput_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NoteInput): _NoteInput {
    return to_candid_record_n7(_uploadFile, _downloadFile, value);
}
function to_candid_NotePatch_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NotePatch): _NotePatch {
    return to_candid_record_n31(_uploadFile, _downloadFile, value);
}
function to_candid_Settings_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Settings): _Settings {
    return to_candid_record_n33(_uploadFile, _downloadFile, value);
}
function to_candid_SortOrder_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SortOrder): _SortOrder {
    return value == SortOrder.title ? {
        title: null
    } : value == SortOrder.favorites ? {
        favorites: null
    } : value == SortOrder.newest ? {
        newest: null
    } : value == SortOrder.oldest ? {
        oldest: null
    } : value;
}
function to_candid_Theme_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Theme): _Theme {
    return value == Theme.dark ? {
        dark: null
    } : value == Theme.automatic ? {
        automatic: null
    } : value == Theme.light ? {
        light: null
    } : value;
}
function to_candid_UserRole_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tagId?: Id;
    favoritesOnly: boolean;
    includeTrashed: boolean;
    folderId?: Id;
}): {
    tagId: [] | [_Id];
    favoritesOnly: boolean;
    includeTrashed: boolean;
    folderId: [] | [_Id];
} {
    return {
        tagId: value.tagId ? candid_some(value.tagId) : candid_none(),
        favoritesOnly: value.favoritesOnly,
        includeTrashed: value.includeTrashed,
        folderId: value.folderId ? candid_some(value.folderId) : candid_none()
    };
}
function to_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title?: string;
    body?: RichText;
    tagIds?: Array<Id>;
    clearFolder?: boolean;
    checklist?: Array<ChecklistItem>;
    clearBody?: boolean;
    folderId?: Id;
    clearTitle?: boolean;
}): {
    title: [] | [string];
    body: [] | [_RichText];
    tagIds: [] | [Array<_Id>];
    clearFolder: [] | [boolean];
    checklist: [] | [Array<_ChecklistItem>];
    clearBody: [] | [boolean];
    folderId: [] | [_Id];
    clearTitle: [] | [boolean];
} {
    return {
        title: value.title ? candid_some(value.title) : candid_none(),
        body: value.body ? candid_some(value.body) : candid_none(),
        tagIds: value.tagIds ? candid_some(value.tagIds) : candid_none(),
        clearFolder: value.clearFolder ? candid_some(value.clearFolder) : candid_none(),
        checklist: value.checklist ? candid_some(value.checklist) : candid_none(),
        clearBody: value.clearBody ? candid_some(value.clearBody) : candid_none(),
        folderId: value.folderId ? candid_some(value.folderId) : candid_none(),
        clearTitle: value.clearTitle ? candid_some(value.clearTitle) : candid_none()
    };
}
function to_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    theme: Theme;
    sortOrder: SortOrder;
    gridView: boolean;
}): {
    theme: _Theme;
    sortOrder: _SortOrder;
    gridView: boolean;
} {
    return {
        theme: to_candid_Theme_n34(_uploadFile, _downloadFile, value.theme),
        sortOrder: to_candid_SortOrder_n25(_uploadFile, _downloadFile, value.sortOrder),
        gridView: value.gridView
    };
}
function to_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    body: RichText;
    tagIds: Array<Id>;
    checklist: Array<ChecklistItem>;
    folderId?: Id;
}): {
    title: string;
    body: _RichText;
    tagIds: Array<_Id>;
    checklist: Array<_ChecklistItem>;
    folderId: [] | [_Id];
} {
    return {
        title: value.title,
        body: value.body,
        tagIds: value.tagIds,
        checklist: value.checklist,
        folderId: value.folderId ? candid_some(value.folderId) : candid_none()
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
